[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
capstone_freelance_escrow = "HWkW19PFehhdgfkGPHnTQTnfhcCQhMqokqGx3Vav7a3N"

[programs.devnet]
capstone_freelance_escrow = "HWkW19PFehhdgfkGPHnTQTnfhcCQhMqokqGx3Vav7a3N"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "wallet.json"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
url = "http://127.0.0.1:8899"
